use whisky_store;
db.dropDatabase();

db.whiskies.insertMany([
  {
    name: "Glenfiddich 21 Year Old",
    region: "Speyside",
    flavours: ["vanilla", "banana", "citrus", "spice"],
    price: 16900,
    abv: 40,
    size: 70,
    image: "./images/product1.png",
  },
  {
    name: "Smokehead Unfiltered Single Malt",
    region: "Islay",
    flavours: [
      "ginger",
      "vanilla",
      "malt",
      "smoke",
      "black pepper",
      "chocolate",
    ],
    price: 3700,
    abv: 46,
    size: 70,
    image: "./images/product2.png",
  },
  {
    name: "Tomatin 14 Year Old",
    region: "Highland",
    flavours: ["toffee", "oak", "honey", "almonds", "red berries"],
    price: 6300,
    abv: 46,
    size: 70,
    image: "./images/product3.png",
  },
  {
    name: "Bowmore 15 Year Old",
    region: "Islay",
    flavours: ["chocolate", "fruit", "smoke"],
    price: 6200,
    abv: 43,
    size: 70,
    image: "./images/product4.png",
  },
  {
    name: "Bunnahabhain 11 Year Old",
    region: "Islay",
    flavours: ["fruit", "smoke", "honey"],
    price: 4700,
    abv: 43,
    size: 70,
    image: "./images/product5.png",
  },
  {
    name: "GlenAllachie 15 Year Old",
    region: "Speyside",
    flavours: ["toffee", "vanilla", "butterscotch", "citrus"],
    price: 6600,
    abv: 46,
    size: 70,
    image: "./images/product6.png",
  },
]);
